# Generated by Django 5.1.6 on 2025-04-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='company_name',
            new_name='company_id',
        ),
    ]
