# Generated by Django 5.1.6 on 2025-03-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_documentform'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentform',
            name='description_DUP',
            field=models.TextField(blank=True, null=True),
        ),
    ]
