# Generated by Django 5.1.6 on 2025-04-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_userprofile_dob_userprofile_certifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='street_address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('internship', 'Internship'), ('part_time', 'Part Time'), ('full_time', 'Full Time'), ('contract', 'Contract')], max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Jobholder'), ('company', 'Company')], max_length=10),
        ),
    ]
