# Generated by Django 5.1.6 on 2025-04-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_userprofile_availability_userprofile_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_field',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
