# Generated by Django 5.1.6 on 2025-04-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('internship', 'Internship'), ('part_time', 'Part Time'), ('full_time', 'Full Time'), ('contract', 'Contract')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='highest_education_level',
            field=models.CharField(blank=True, choices=[('internship', 'Internship'), ('part_time', 'Part Time'), ('full_time', 'Full Time'), ('contract', 'Contract')], max_length=20),
        ),
    ]
