# Generated by Django 5.1.6 on 2025-04-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_userprofile_employment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='highest_education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD')], max_length=20),
        ),
    ]
