# Generated by Django 5.1.6 on 2025-04-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_userprofile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='work_field',
            field=models.CharField(blank=True, choices=[(True, 'Available immediately'), (False, 'Requires notice period')], max_length=20),
        ),
    ]
