# Generated by Django 5.1.6 on 2025-04-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_userprofile_work_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ready_to_work',
            field=models.CharField(blank=True, choices=[(True, 'Available immediately'), (False, 'Requires notice period')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_field',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
