# Generated by Django 5.1.6 on 2025-04-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_userprofile_ready_to_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ready_to_work',
            field=models.CharField(blank=True, choices=[('True', 'Available immediately'), ('False', 'Requires notice period')], max_length=20),
        ),
    ]
