# Generated by Django 5.1.6 on 2025-04-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_userprofile_ready_to_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ready_to_work',
            field=models.CharField(blank=True, choices=[('Available immediately', 'Available immediately'), ('Requires notice period', 'Requires notice period')], max_length=50),
        ),
    ]
