# Generated by Django 5.1.6 on 2025-04-10 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_userprofile_ready_to_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.companyprofile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='App.companyprofile'),
        ),
        migrations.AlterField(
            model_name='document',
            name='owner_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='App.companyprofile'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='country',
            field=models.CharField(blank=True, choices=[('Nigeria', 'Nigeria'), ('Ghana', 'Ghana'), ('Kenya', 'Kenya'), ('South Africa', 'South Africa')], max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
