# Generated by Django 5.1.6 on 2025-04-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_feedback_company_alter_job_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='work_mode',
            field=models.TextField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on_site', 'On Site')], null=True),
        ),
    ]
