# Generated by Django 5.1.6 on 2025-04-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_userprofile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
    ]
