# Generated by Django 5.1.6 on 2025-04-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_userprofile_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='country',
            new_name='job_location',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_country',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
