# Generated by Django 5.1.6 on 2025-06-05 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_userprofile_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_format',
            field=models.CharField(choices=[('pdf', 'pdf'), ('doc', 'doc'), ('docx', 'docx'), ('txt', 'txt')], default='pdf', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('Resume', 'Resume'), ('Certification', 'Certification'), ('CV', 'CV')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='App.job'),
        ),
    ]
