# Generated by Django 5.1.6 on 2025-06-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_document_file_format_alter_document_file_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='application',
            name='next_step',
            field=models.CharField(choices=[('Awaiting response', 'Awaiting response'), ('Technical Interview', 'Technical Interview'), ('N/A', 'N/A'), ('Welcome aboard', 'Welcome aboard')], default='Awaiting response', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD'), ('EUR', 'EUR')], default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On site', 'On Site')], default='Remote', max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected')], default='Applied', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Contract', 'Contract')], default='Full Time', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
