# Generated by Django 5.1.6 on 2025-06-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_application_unique_user_job_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Human Resources', 'Human Resources'), ('Finance', 'Finance'), ('Customer Support', 'Customer Support'), ('Design', 'Design'), ('Product Management', 'Product Management'), ('Operations', 'Operations'), ('Data Science', 'Data Science'), ('Content Creation', 'Content Creation'), ('Research and Development', 'Research and Development'), ('Quality Assurance', 'Quality Assurance'), ('Administration', 'Administration'), ('Business Development', 'Business Development'), ('Information Technology', 'Information Technology'), ('Project Management', 'Project Management'), ('Supply Chain Management', 'Supply Chain Management'), ('Public Relations', 'Public Relations'), ('Consulting', 'Consulting')], default='Engineering', max_length=255),
        ),
    ]
