# Generated by Django 5.1.6 on 2025-06-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_job_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='company_id',
            new_name='company_reg_num',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='annual_growth_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='awards',
            field=models.TextField(blank=True, help_text='Enter awards seperated by commas', null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Enter awards seperated by commas', null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='core_tech',
            field=models.TextField(blank=True, help_text='Enter tech tools seperated by commas', null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='founded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='headquarters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='mission_statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='parent_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('FinTech', 'FinTech'), ('HealthTech', 'HealthTech'), ('EdTech', 'EdTech'), ('E-commerce', 'E-commerce'), ('Agritech', 'Agritech'), ('Logistics', 'Logistics'), ('Real Estate', 'Real Estate'), ('Telecommunications', 'Telecommunications'), ('Entertainment', 'Entertainment'), ('Travel and Tourism', 'Travel and Tourism'), ('Manufacturing', 'Manufacturing'), ('Energy', 'Energy'), ('Retail', 'Retail'), ('Media', 'Media'), ('Construction', 'Construction'), ('Consulting', 'Consulting'), ('Information Technology', 'Information Technology'), ('Food and Beverage', 'Food and Beverage'), ('Transportation', 'Transportation'), ('Non-profit', 'Non-profit'), ('Government', 'Government'), ('Fashion', 'Fashion'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Human Resources', 'Human Resources'), ('Finance', 'Finance'), ('Customer Support', 'Customer Support'), ('Design', 'Design'), ('Product Management', 'Product Management'), ('Operations', 'Operations'), ('Data Science', 'Data Science'), ('Content Creation', 'Content Creation'), ('Research and Development', 'Research and Development'), ('Quality Assurance', 'Quality Assurance'), ('Administration', 'Administration'), ('Business Development', 'Business Development'), ('Information Technology', 'Information Technology'), ('Project Management', 'Project Management'), ('Supply Chain Management', 'Supply Chain Management'), ('Public Relations', 'Public Relations'), ('Consulting', 'Consulting'), ('Other', 'Other')], default='Engineering', max_length=255),
        ),
    ]
