# Generated by Django 5.1.6 on 2025-06-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_rename_company_id_companyprofile_company_reg_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='hire_status',
            field=models.CharField(choices=[('Hiring', 'Hiring'), ('Applications Closed', 'Applications Closed')], default='Hiring', max_length=100),
        ),
    ]
