# Generated by Django 5.1.6 on 2025-06-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_companyprofile_hire_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='description',
        ),
    ]
