# Generated by Django 5.1.6 on 2025-06-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_remove_companyprofile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On site', 'On Site')], null=True),
        ),
    ]
