# Generated by Django 5.1.6 on 2025-06-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_alter_companyprofile_work_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_reg_num',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
