# Generated by Django 5.1.6 on 2025-06-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_remove_application_resume_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='portfolio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
