# Generated by Django 5.1.6 on 2025-06-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0041_remove_application_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On site', 'On Site')], max_length=255, null=True),
        ),
    ]
