# Generated by Django 5.1.6 on 2025-06-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0043_alter_document_file_alter_userprofile_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='max_salary',
        ),
        migrations.AddField(
            model_name='job',
            name='min_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
