# Generated by Django 5.1.6 on 2025-06-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0044_rename_salary_job_max_salary_job_min_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Senior Level', 'Senior Level'), ('Expert', 'Expert')], default='Senior Level', max_length=50),
        ),
    ]
