# Generated by Django 5.1.6 on 2025-06-18 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0045_job_experience_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Human Resources', 'Human Resources'), ('Finance', 'Finance'), ('Education', 'Education'), ('Customer Support', 'Customer Support'), ('Design', 'Design'), ('Product Management', 'Product Management'), ('Operations', 'Operations'), ('Data Science', 'Data Science'), ('Content Creation', 'Content Creation'), ('Research and Development', 'Research and Development'), ('Quality Assurance', 'Quality Assurance'), ('Administration', 'Administration'), ('Business Development', 'Business Development'), ('Information Technology', 'Information Technology'), ('Project Management', 'Project Management'), ('Supply Chain Management', 'Supply Chain Management'), ('Public Relations', 'Public Relations'), ('Consulting', 'Consulting'), ('Other', 'Other')], default='Engineering', max_length=255),
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employment_type', models.CharField(choices=[('Internship', 'Internship'), ('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Contract', 'Contract')], max_length=20)),
                ('job_location', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
