# Generated by Django 5.1.6 on 2025-06-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0046_alter_job_department_employment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='work_mode',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('On site', 'On Site')], default='Remote', max_length=20),
            preserve_default=False,
        ),
    ]
