# Generated by Django 5.1.6 on 2025-06-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0050_alter_employment_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='current_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
