# Generated by Django 5.1.6 on 2025-06-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0053_skill_remove_userprofile_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='App.skill'),
        ),
    ]
