# Generated by Django 5.1.6 on 2025-06-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0055_alter_userprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portfolio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
