# Generated by Django 5.1.6 on 2025-06-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0056_userprofile_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Enter certifications seperated by commas', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='project',
            field=models.CharField(blank=True, help_text='Enter certifications seperated by commas', null=True),
        ),
    ]
