# Generated by Django 5.1.6 on 2025-06-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0057_alter_userprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='project',
            field=models.TextField(blank=True, help_text='Enter certifications seperated by commas', null=True),
        ),
    ]
