# Generated by Django 5.1.6 on 2025-06-24 11:44

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0059_remove_application_availability_application_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
