# Generated by Django 5.1.6 on 2025-06-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0060_alter_application_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('Entry Level', 'Entry'), ('Mid Level', 'Mid'), ('Senior Level', 'Senior'), ('Expert', 'Expert')], default='Senior Level', max_length=50),
        ),
    ]
