# Generated by Django 5.1.6 on 2025-06-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0063_job_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='work_mode_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
