# Generated by Django 5.1.6 on 2025-06-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0064_job_work_mode_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
