# Generated by Django 5.1.6 on 2025-06-28 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0065_job_qualification_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='employment_names', to='App.companyprofile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TeamManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateField()),
                ('left', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Pending Approval', 'Pending Approval'), ('Served', 'Served')], default='Pending Approval', max_length=20)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_worforce', to='App.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worfforce', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
