# Generated by Django 5.1.6 on 2025-06-28 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0066_employment_company_teammanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employed', to='App.companyprofile'),
        ),
    ]
