# Generated by Django 5.1.6 on 2025-06-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0067_alter_employment_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='company',
        ),
    ]
