# Generated by Django 5.1.6 on 2025-06-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0068_remove_employment_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammanagement',
            name='joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
