# Generated by Django 5.1.6 on 2025-06-30 00:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0069_alter_teammanagement_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
