# Generated by Django 5.1.6 on 2025-06-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0070_companyprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammanagement',
            old_name='status',
            new_name='user_status',
        ),
        migrations.AddField(
            model_name='teammanagement',
            name='company_status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Pending', 'Pending'), ('Inactive', 'Inactive')], default='Pending Approval', max_length=20),
        ),
        migrations.AddField(
            model_name='teammanagement',
            name='employee_ID',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
