# Generated by Django 5.1.6 on 2025-06-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0071_rename_status_teammanagement_user_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammanagement',
            name='joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
