# Generated by Django 5.1.6 on 2025-06-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0072_alter_teammanagement_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammanagement',
            name='company_status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Pending', 'Pending'), ('Served', 'Served')], default='Pending', max_length=20),
        ),
    ]
