# Generated by Django 5.1.6 on 2025-06-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0073_alter_teammanagement_company_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teammanagement',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='unique_user_job_team_management'),
        ),
    ]
